services:
  - type: web
    name: dellys-mini-market
    env: node
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
